helm-2-bug-fix
kiwigrid/helm-gradle-plugin pull request #14
Opened 2021-03-29 20:00 UTC by wind57

2021-03-29 20:01 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java
> +			if(HelmPlugin.isVersion3OrNewer(getVersion())) {
unfortunately, I got it wrong the previous time for where the place is for `repositories.yalm` for `helm2` and `helm3` on Mac. I am sorry to have missed that before

2021-03-30 07:43 UTC, jekkel requested changes

2021-03-30 07:43 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java
> +			if(HelmPlugin.isVersion3OrNewer(getVersion())) {
If the path on Mac for helm 2 is in the users home directory it is probably affected by the given command line flag which tells helm to use a different home directory (helm home defaults to `$HOME/.helm`). The plugin does this to isolate the project helm installation from all other helm installations on the system. Could you please double check:
* helm 2 on mac ignores the overridden helm home directory (if not: let the case be handled by the existing code)
* helm 3 on mac doesn't feature or respect the option and thus overriding config file location by command line cannot be done

2021-03-31 14:37 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/tasks/RepoSyncTask.java
> +			if(HelmPlugin.isVersion3OrNewer(getVersion())) {
I am going to close this and move the discussion elsewhere, since this is not as trivial as I hope it would be.

2021-03-31 14:37 UTC, closed without merging