Ability to specify custom path for helm charts and tests
kiwigrid/helm-gradle-plugin pull request #27
Opened 2021-08-26 17:46 UTC by wusik

fixes #25

2021-08-27 12:05 UTC, jekkel requested changes
Hey @wusik , thanks for your contribution! You touched files that made some inconsistencies obvious. IMO we should restrict each task to deal with a single chart only and clarify in the readme that multiple charts per project needs "manual" task registrations - once per chart - with different source folders configured. I guess we'd need to provide a test case for this, too.

We'd appreciate if you'd be ok with investing a little bit more time into this!

2021-08-30 10:04 UTC, wusik commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		File[] chartFolders = getOutputDirectory().listFiles(file -> file.isDirectory() && matchesChartName(file));
Oh, looks like I left my eyes at home =). You suggested to use the output directory for each build of the task separately. That's exactly what would solve the problem

2021-08-30 11:15 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +		} catch (IOException e) {
Indeed I missed that using try-with-resources implicitly calls `close` which throws IOE. So your absolutely right in widening the exception type everywhere.

2021-08-30 11:16 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmBuildTask.java
> +		} catch (FileNotFoundException e) {
Yes, let's widen the `throws` declaration to IOE.

2021-08-30 11:18 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		onlyIf(element -> tests.getOrElse(getTestSourceDir()).getAsFile().exists());
Indeed, your right, missed the provider `get()`.

2021-08-30 11:22 UTC, jekkel commented on README.md
> +    tests = project.getLayout().getProjectDirectory().dir('/helm/test')
Totally agree, we should use the same approach in build and test task.

I think it might still be possible to assign a file to a directory property due to the inherited `FileSystemLocationProperty.set(File file);` method (probably add a test before making the change!) so maybe we're not having such a big breaking change here at all.

2021-08-30 12:35 UTC, wusik commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		File[] chartFolders = getOutputDirectory().listFiles(file -> file.isDirectory() && matchesChartName(file));
Hey, @jekkel, it looks like I got excited too soon. With the current architecture, it is quite problematic to make N independent pairs of tasks. 
Maybe we should allow to build multiple charts in one task? 
 - Either we set (or leave default) `source` directly to the directory which contains contents of chart and then build only it and all tests apply to it (needed for backward compatibility). The test will fail if the Output contains more than one chart.
- Or we specify source in the directory which contains several charts. Then all of them will build at once. The tests for a particular chart will be found in the folder ${tests}/${chartName} and the other tests will be ignored. I don't think it's necessary to maintain backward compatibility here, because in general the case of multiple charts doesn't work. We can further improve this behavior by adding the ability to specify the relation between the name of the chart and the directory containing the tests for it.

2021-08-30 12:46 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		File[] chartFolders = getOutputDirectory().listFiles(file -> file.isDirectory() && matchesChartName(file));
> With the current architecture, it is quite problematic to make N independent pairs of tasks.

Could you elaborate on this? From my understanding given the initial "default" situation:

* the plugin is configured using the `helm` extension
* one instance of each task is registered automatically and configured with the extensions value

One could add another set of tasks like so:

```
tasks.register("helmSecondChartBuild", HelmBuildTask) {
  dependsOn tasks.named("helmRepoSync")
  expansions = helm.expansions
  copyFrom helm
  // custom configuration
  source = file('src/main/secondchart')
  outputDirectory = file("$buildDir/helm/repo2")
}
tasks.register("helmSecondChartTest", HelmTestTask) {
  dependsOn tasks.named("helmSecondChartBuild")
  copyFrom helm
  // custom configuration
  source = file('src/test/secondchart')
  outputDirectory = file("$buildDir/helm/repo2")
}
// probably do the same for deploy task
```

I did not try that but can't see any issues with it, do you?

2021-08-30 15:41 UTC, wind57 commented on README.md
> +    //this will override helm charts source directory
I have a nitpick here on the "helm charts source directory". This is not a source directory for a _helm chart_. This is source directory of the manifests that make it, eventually, a helm chart. How about:

```
helmChartBuild() {
      // source folder for the charts manifest files. just an example here, provide your own as needed
      source = file(project.projectDir.getAbsolutePath() + "/helm")
}
```

Again, this is a nitpick, really.

2021-08-30 16:17 UTC, wind57 commented on README.md
> +    tests = project.getLayout().getProjectDirectory().dir('/helm/test')
I agree that a test is going to be needed. We override the `source` in some of our projects, via : 

```
tasks {
    helmChartBuild {
        source.set(file(....))
    }
}
```

So if you change to a directory, it could be a breaking change. It is easy to fix, but a clear documentation part on the release is going to be needed.

2021-08-30 16:27 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +		} catch (IOException e) {
so effectively this portion of the code does not require any changes at all, right?

2021-08-30 16:32 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
>  			throw new RuntimeException(e);
you could throw the more idiomatic `throw  new UncheckedIOException(e);`...

2021-08-30 16:33 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +				return Collections.emptyList();
btw, why did you change to a `List`?

2021-08-30 16:35 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmBuildTask.java
>  import java.util.Map;
in this same file can you make `private Property<File> source;`, `final` please? if you are already here...

2021-08-30 16:39 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmBuildTask.java
> +			Map contents = HelmPlugin.YAML.load(inputStream);
can you get rid of the raw types here please? As well as in `setExpansions` method... thank you!

2021-08-30 16:44 UTC, wind57 commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		File[] chartFolders = getOutputDirectory().listFiles(file -> file.isDirectory() && matchesChartName(file));
@jekkel this is a lovely example! can we also have this as part of the documentation also? would be very helpful.

2021-08-31 09:57 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +		} catch (IOException e) {
indeed, if we omit the auto closed try with resources there won't be a declared exception and hence no change at all.

2021-08-31 09:58 UTC, wusik commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		File[] chartFolders = getOutputDirectory().listFiles(file -> file.isDirectory() && matchesChartName(file));
Eh. That was on the surface, but I missed that there is an option to override `outputDirectory` for the task. 
No problem then, I'll add it to the review soon.

@wind57 I will add this example to the Readme

2021-08-31 09:59 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +				return Collections.emptyList();
it has been converted in several places to a list and I think @wusik just inlined that conversion.

2021-08-31 09:59 UTC, wusik commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +		} catch (IOException e) {
@wind57 sure, there will be no change here.

2021-08-31 10:00 UTC, jekkel commented on src/main/java/com/kiwigrid/k8s/helm/tasks/HelmTestTask.java
> +		File[] chartFolders = getOutputDirectory().listFiles(file -> file.isDirectory() && matchesChartName(file));
Go for it! ;)

Probably this deserves a test case then.

2021-08-31 10:14 UTC, wusik commented on README.md
> +    //this will override helm charts source directory
About the second suggestion. I think it has more to do with the general rules of working with gradle. 
But I can add as an additional option.

2021-08-31 10:21 UTC, wusik commented on src/main/java/com/kiwigrid/k8s/helm/HelmPlugin.java
> +				return Collections.emptyList();
I moved the list creation inside because the iterator created by YAML is lazy and we can't use it outside the method if we close `FileInputStream` here. Both uses of this method immediately converted the result to a `List`. So I changed the result of this method to `List` and accordingly had to return an empty `List` instead of `Set`

2021-08-31 12:32 UTC, wusik commented
@jekkel @wind57 I've pushed changes to repo. 
Please take a look at it. I hope I didn't miss anything important.

2021-08-31 12:56 UTC, wusik commented
Sry. Missed some changes to commit.  It should be ok now.

2021-08-31 13:11 UTC, jekkel requested changes
Great job, thank you! Only some minor style issues remain, I think we can merge this soon.

2021-08-31 13:11 UTC, jekkel commented on src/test/groovy/com/kiwigrid/k8s/helm/TestProjects.groovy
> +        """.stripIndent()
please fix indentation here.

2021-08-31 13:11 UTC, jekkel commented on src/test/groovy/com/kiwigrid/k8s/helm/TestProjects.groovy
> +        """.stripIndent()
this last line forces all other lines to be indented by 4 spaces (because `stripIndent()` looks for the least indented line to determine the indent) when it shouldn't be indented at all. If I see it correctly, we had this issues in different places already. Probably you can fix that? I think that would improve readability a bit.

2021-08-31 13:11 UTC, jekkel commented on src/test/groovy/com/kiwigrid/k8s/helm/TestProjects.groovy
> +        """.stripIndent()
same here.

2021-08-31 13:51 UTC, wusik commented on src/test/groovy/com/kiwigrid/k8s/helm/TestProjects.groovy
> +        """.stripIndent()
Is that what you meant?
```suggestion
 """.stripIndent()
```

May be I should replace all tabs in file with 4 spaces, and after that count and pass right number of chars directly to `stripIndent`? Like this
```suggestion
        """.stripIndent(4)
```

2021-08-31 13:54 UTC, jekkel commented on src/test/groovy/com/kiwigrid/k8s/helm/TestProjects.groovy
> +        """.stripIndent()
Actually the other way around:
```suggestion
            """.stripIndent()
```

2021-09-02 08:25 UTC, jekkel approved these changes

2021-09-02 08:33 UTC, merged